### ISSUE TITLE
DIS Interface

### ISSUE THREAD

**Issue by Manny-SystemsEngineer** [Manny-SystemsEngineer/Open-CGF#2]
Integrate Open-DIS into Open-CGF.

Actions:
- [ ] Add Open-DIS library to external libraries
- [ ] Create unit test to prove functionality (both send and receive)
- [ ] Add documentation to wiki
