### ISSUE TITLE
Visualisation

### ISSUE THREAD

**Issue by Manny-SystemsEngineer** [Manny-SystemsEngineer/Open-CGF#3]
Integrate NASA Whirlwind into Open-CGF.

Actions:
- [x] Add NASA Whirlwind library to external libraries
- [ ] Create unit test to prove functionality (including plotting of DIS data) 
- [ ] Add documentation to wiki

**Comment by Manny-SystemsEngineer** [comment]
Got multiple tactical symbols working with tactical symbol generator
