### ISSUE TITLE
Terrain Database

### ISSUE THREAD

**Issue by Manny-SystemsEngineer** [Manny-SystemsEngineer/Open-CGF#5]
Store for terrains to be used by visualisation component.

Actions:
- [ ] Check supported data formats
- [ ] Choose database server
- [ ] Decide how to package
- [ ] Set-up and configure
- [ ] Source and import data
- [ ] Test
- [ ] Document
